import assert from 'node:assert/strict';
import test from 'node:test';
import { PerformanceStore } from '../src/store.ts';

function configuration(store: PerformanceStore) {
  const workspace = store.workspace();
  return {
    employeeId: workspace.employees.find((item) => item.status === 'ACTIVE')!.id,
    indicators: workspace.indicators.map(({ definitionId, weight, target }) => ({
      definitionId,
      weight,
      target,
    })),
    reviewers: workspace.reviewers.map(({ id, name, weight }) => ({ id, name, weight })),
  };
}

function actuals(store: PerformanceStore) {
  const values = [112, 92, 88];
  return {
    values: Object.fromEntries(store.workspace().indicators.map((item, index) => [item.id, values[index]])),
  };
}

function selfScores(store: PerformanceStore) {
  const values = [39, 32, 23];
  return {
    scores: Object.fromEntries(store.workspace().indicators.map((item, index) => [item.id, values[index]])),
  };
}

function reviewerScores(store: PerformanceStore) {
  const matrix = [
    [38, 32, 23],
    [37, 31, 22],
    [39, 33, 24],
  ];
  const workspace = store.workspace();
  return {
    scores: workspace.reviewers.flatMap((reviewer, reviewerIndex) =>
      workspace.indicators.map((indicator, indicatorIndex) => ({
        reviewerId: reviewer.id,
        indicatorId: indicator.id,
        score: matrix[reviewerIndex][indicatorIndex],
      })),
    ),
  };
}

test('synthetic scenario advances through the complete performance lifecycle', () => {
  const store = new PerformanceStore();
  try {
    assert.equal(store.workspace().stage, 'CONFIGURATION');
    assert.equal(store.performAction('submit-configuration', configuration(store)).stage, 'DATA_ENTRY');
    assert.equal(store.performAction('submit-actuals', actuals(store)).stage, 'SELF_REVIEW');
    assert.equal(store.performAction('submit-self-review', selfScores(store)).stage, 'REVIEW');
    assert.equal(store.performAction('submit-reviewers', reviewerScores(store)).stage, 'CALCULATION');
    assert.equal(store.performAction('calculate-and-settle').stage, 'LOCKED');
    const workspace = store.workspace();
    assert.equal(workspace.finalScore, 94.8);
    assert.equal(workspace.grade, 'A');
    const itemTotal = workspace.indicators.reduce((sum, item) => sum + (item.finalScore || 0), 0);
    assert.equal(Math.round(itemTotal * 100) / 100, 94.8);
    assert.throws(() => store.performAction('calculate-and-settle'), /已经结算锁定/);
  } finally {
    store.close();
  }
});

test('reset affects only the isolated synthetic scenario', () => {
  const store = new PerformanceStore();
  try {
    store.performAction('submit-configuration', configuration(store));
    const reset = store.reset();
    assert.equal(reset.stage, 'CONFIGURATION');
    assert.equal(reset.scenarioId, 'SYN-PERF-2026-Q3');
    assert.equal(reset.audits[0]?.action, 'SCENARIO_RESET');
  } finally {
    store.close();
  }
});

test('business actions reject out-of-order calls and persist across page responsibilities', () => {
  const store = new PerformanceStore();
  try {
    assert.throws(() => store.performAction('submit-actuals'), /当前阶段只允许/);
    assert.equal(store.performAction('submit-configuration', configuration(store)).stage, 'DATA_ENTRY');
    assert.equal(store.performAction('submit-actuals', actuals(store)).stage, 'SELF_REVIEW');
    assert.equal(store.performAction('submit-self-review', selfScores(store)).stage, 'REVIEW');
    assert.equal(store.performAction('submit-reviewers', reviewerScores(store)).stage, 'CALCULATION');
    assert.equal(store.performAction('calculate-and-settle').stage, 'LOCKED');
  } finally {
    store.close();
  }
});

test('business inputs are validated instead of generated by the backend', () => {
  const store = new PerformanceStore();
  try {
    const invalid = configuration(store);
    invalid.indicators[0].weight = 10;
    assert.throws(() => store.performAction('submit-configuration', invalid), /100/);
    const valid = configuration(store);
    const selectedEmployee = store.workspace().employees.find((item) => item.id === valid.employeeId)!;
    assert.equal(store.performAction('submit-configuration', valid).employee.name, selectedEmployee.name);
    assert.throws(() => store.performAction('submit-actuals', { values: {} }), /实际值/);
  } finally {
    store.close();
  }
});

test('master data can be created, edited, and guarded by domain rules', () => {
  const store = new PerformanceStore();
  try {
    let workspace = store.saveOrganization({
      code: 'SYN-QA',
      name: '质量中心',
      manager: '测试负责人',
      status: 'ACTIVE',
    });
    const organization = workspace.organizations.find((item) => item.code === 'SYN-QA')!;
    workspace = store.saveEmployee({
      employeeNo: 'SYN-9001',
      name: '质量专员',
      position: '测试工程师',
      organizationId: organization.id,
      status: 'ACTIVE',
    });
    assert.equal(
      workspace.employees.some((item) => item.employeeNo === 'SYN-9001'),
      true,
    );
    assert.throws(() => store.saveOrganization({ ...organization, status: 'INACTIVE' }), /在职人员/);
    workspace = store.saveIndicatorDefinition({
      code: 'SYN-QUAL',
      name: '缺陷闭环率',
      category: '质量',
      mode: 'SYSTEM',
      unit: '%',
      defaultWeight: 20,
      defaultTarget: 98,
      status: 'ACTIVE',
    });
    assert.equal(
      workspace.indicatorDefinitions.some((item) => item.code === 'SYN-QUAL'),
      true,
    );
  } finally {
    store.close();
  }
});
