import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import test from 'node:test';
import { assessLiveBaseline } from '../scripts/check-live-baseline.mjs';
import {
  createConnectorIdMap,
  createLabRuntimeModule,
  createPageRouteMap,
  createResourceFieldIdMap,
  createResourceIdMap,
  createResourceProcessCodeMap,
  digest,
  extractJsonDocuments,
  findCanvasComponent,
  stableValue,
} from '../scripts/lib.mjs';
import {
  createFlowboardConnectorActions,
  validateFlowboardApiContract,
} from '../scripts/generate-flowboard-connector-actions.mjs';
import { createCanvasPublishSource, createCanvasRuntimeSource } from '../scripts/tailwind-build-lib.mjs';

test('extractJsonDocuments ignores command banners and preserves nested JSON', () => {
  const documents = extractJsonDocuments('banner\n{"success":true,"data":{"value":1}}\nfooter');
  assert.deepEqual(documents, [{ success: true, data: { value: 1 } }]);
});

test('semantic digest ignores volatile modification timestamps', () => {
  const first = { gmtModified: 1, pages: [{ b: 2, a: 1 }] };
  const second = { pages: [{ a: 1, b: 2 }], gmtModified: 999 };
  assert.deepEqual(stableValue(first), stableValue(second));
  assert.equal(digest(first), digest(second));
});

test('findCanvasComponent discovers nested YidaCodeCanvas', () => {
  const canvas = { componentName: 'YidaCodeCanvas', props: { runtimeCode: 'code', importedModules: [] } };
  const descriptor = { componentName: 'YidaCodeCanvas', package: '@ali/vc-deep-yida' };
  assert.equal(findCanvasComponent({ pages: [{ componentsMap: [descriptor], tree: [canvas] }] }), canvas);
  assert.equal(findCanvasComponent({ pages: [] }), null);
});

test('Tailwind build keeps generated CSS out of author source', () => {
  const authorSource =
    "import React from 'react';\nimport './styles.css';\nimport { getLabPageUrl } from '@yida-lab/runtime';\nexport default React.Fragment;\n";
  const output = createCanvasPublishSource(authorSource, '.lab-grid{display:grid}', {
    'tailwind.runtime': '/APP_TEST/workbench/FORM_RUNTIME',
  });
  assert.match(authorSource, /import '\.\/styles\.css'/);
  assert.doesNotMatch(authorSource, /GENERATED_TAILWIND_CSS/);
  assert.doesNotMatch(output, /import '\.\/styles\.css'/);
  assert.match(output, /Generated by npm run build:canvas\. Do not edit\./);
  assert.match(output, /const GENERATED_TAILWIND_CSS/);
  assert.match(output, /const YIDA_LAB_PAGE_ROUTES/);
  assert.match(output, /FORM_RUNTIME/);
  assert.match(output, /\.lab-grid\{display:grid\}/);
});

test('Canvas build injects logical page routes only into generated output', () => {
  const authorSource =
    "import { getLabPageUrl } from '@yida-lab/runtime';\nconst url = getLabPageUrl('page.two');\nexport default url;\n";
  const output = createCanvasRuntimeSource(authorSource, {
    'page.two': '/APP_TEST/workbench/FORM_TWO',
  });
  assert.doesNotMatch(authorSource, /APP_TEST|FORM_TWO/);
  assert.doesNotMatch(output, /@yida-lab\/runtime/);
  assert.match(output, /\/APP_TEST\/workbench\/FORM_TWO/);
});

test('page route map uses logical keys and supports target-free public builds', () => {
  const manifest = {
    application: { appType: 'APP_TEST' },
    pages: [
      { key: 'page.one', formUuid: 'FORM_ONE' },
      { key: 'page.two', formUuid: null },
    ],
  };
  assert.deepEqual(createPageRouteMap(manifest), {
    'page.one': '/APP_TEST/workbench/FORM_ONE',
    'page.two': '#unconfigured-page=page.two',
  });
  assert.throws(() => createPageRouteMap(manifest, { requireRemote: true }), /page.two/);
});

test('local preview and Canvas builds can share one virtual runtime module', () => {
  const source = createLabRuntimeModule({
    routes: { 'flowboard.board': '/APP_TEST/workbench/FORM_FLOWBOARD' },
    services: { flowboardApi: 'http://127.0.0.1:4318/api' },
    connectors: { flowboardApi: 'Http_TEST' },
    resources: { 'platform.formSandbox': 'FORM_SANDBOX' },
    resourceFields: { 'platform.formSandbox': { experimentTag: 'textField_TEST' } },
    resourceProcessCodes: { 'platform.processSandbox': 'TPROC_TEST' },
    profile: {
      stage: 'test',
      defaultTransport: 'connector',
      allowDirectOverride: true,
      expectedAppType: 'APP_TEST',
    },
  });
  assert.match(source, /getLabPageUrl/);
  assert.match(source, /getLabServiceUrl/);
  assert.match(source, /FORM_FLOWBOARD/);
  assert.match(source, /127\.0\.0\.1:4318/);
  assert.match(source, /Http_TEST/);
  assert.match(source, /allowDirectOverride/);
  assert.match(source, /expectedAppType/);
  assert.match(source, /getLabResourceId/);
  assert.match(source, /FORM_SANDBOX/);
  assert.match(source, /getLabResourceFieldId/);
  assert.match(source, /textField_TEST/);
  assert.match(source, /getLabResourceProcessCode/);
  assert.match(source, /TPROC_TEST/);
});

test('resource map keeps real form IDs out of public configuration', () => {
  const manifest = {
    resources: [{ key: 'platform.formSandbox', formUuid: null }],
  };
  assert.deepEqual(createResourceIdMap(manifest), {
    'platform.formSandbox': '#unconfigured-resource=platform.formSandbox',
  });
  assert.throws(() => createResourceIdMap(manifest, { requireConfigured: true }), /formUuid/);
});

test('resource field map requires explicit field IDs for guarded builds', () => {
  const manifest = {
    resources: [{ key: 'platform.formSandbox', fields: { experimentTag: null } }],
  };
  assert.deepEqual(createResourceFieldIdMap(manifest), {
    'platform.formSandbox': {
      experimentTag: '#unconfigured-resource-field=platform.formSandbox.experimentTag',
    },
  });
  assert.throws(() => createResourceFieldIdMap(manifest, { requireConfigured: true }), /fieldId/);
});

test('process resource map keeps process codes environment-specific', () => {
  const manifest = {
    resources: [{ key: 'platform.processSandbox', kind: 'process', processCode: null }],
  };
  assert.deepEqual(createResourceProcessCodeMap(manifest), {
    'platform.processSandbox': '#unconfigured-process=platform.processSandbox',
  });
  assert.throws(() => createResourceProcessCodeMap(manifest, { requireConfigured: true }), /processCode/);
});

test('connector map requires explicit environment mapping for guarded builds', () => {
  const manifest = { connectors: [{ key: 'flowboardApi', connectorId: null }] };
  assert.deepEqual(createConnectorIdMap(manifest), {
    flowboardApi: '#unconfigured-connector=flowboardApi',
  });
  assert.throws(() => createConnectorIdMap(manifest, { requireConfigured: true }), /connectorId/);
});

test('Flowboard API contract generates deterministic safe connector actions', async () => {
  const contract = JSON.parse(
    await fs.readFile(new URL('../contracts/flowboard-api.contract.json', import.meta.url), 'utf8'),
  );
  assert.deepEqual(validateFlowboardApiContract(contract), { operationCount: 5, actionCount: 5 });
  const actions = createFlowboardConnectorActions(contract);
  assert.deepEqual(
    actions.map((action) => action.operationId),
    ['health_get', 'tasks_list', 'tasks_create', 'tasks_update', 'tasks_remove'],
  );
  assert.equal(actions.find((action) => action.operationId === 'tasks_update').method, 'post');
  assert.equal(actions.find((action) => action.operationId === 'tasks_remove').url, 'api/tasks/{id}/delete');
});

test('tracked Tailwind author source uses a normal CSS import', async () => {
  const authorSource = await fs.readFile(
    new URL('../labs/canvas-tailwind/src/TailwindBuildTimeProbe.canvas.jsx', import.meta.url),
    'utf8',
  );
  assert.match(authorSource, /import '\.\/styles\.css'/);
  assert.match(authorSource, /from '@yida-lab\/runtime'/);
  assert.doesNotMatch(authorSource, /GENERATED_TAILWIND_CSS/);
  assert.doesNotMatch(authorSource, /__TAILWIND_CSS_JSON__/);
});

test('live guard allows only a blank page without a baseline', () => {
  assert.deepEqual(
    assessLiveBaseline({
      baseline: null,
      appType: 'APP_TEST',
      formUuid: 'FORM_TEST',
      liveSemanticSha256: 'blank',
      runtimeCode: '',
    }),
    { mode: 'initial-blank-page' },
  );
  assert.throws(
    () =>
      assessLiveBaseline({
        baseline: null,
        appType: 'APP_TEST',
        formUuid: 'FORM_TEST',
        liveSemanticSha256: 'occupied',
        runtimeCode: 'existing code',
      }),
    /停止首次发布/,
  );
});

test('live guard blocks drift and accepts an exact baseline', () => {
  const baseline = {
    appType: 'APP_TEST',
    formUuid: 'FORM_TEST',
    liveSemanticSha256: 'expected',
  };
  assert.deepEqual(
    assessLiveBaseline({
      baseline,
      appType: 'APP_TEST',
      formUuid: 'FORM_TEST',
      liveSemanticSha256: 'expected',
      runtimeCode: 'code',
    }),
    { mode: 'baseline-match' },
  );
  assert.throws(
    () =>
      assessLiveBaseline({
        baseline,
        appType: 'APP_TEST',
        formUuid: 'FORM_TEST',
        liveSemanticSha256: 'changed',
        runtimeCode: 'code',
      }),
    /线上页面已偏离/,
  );
});
