import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import test from 'node:test';
import { assessLiveBaseline } from '../scripts/check-live-baseline.mjs';
import {
  createPageRouteMap,
  digest,
  extractJsonDocuments,
  findCanvasComponent,
  stableValue,
} from '../scripts/lib.mjs';
import { createCanvasPublishSource, createCanvasRuntimeSource } from '../scripts/tailwind-build-lib.mjs';

test('extractJsonDocuments ignores command banners and preserves nested JSON', () => {
  const documents = extractJsonDocuments('banner\n{"success":true,"data":{"value":1}}\nfooter');
  assert.deepEqual(documents, [{ success: true, data: { value: 1 } }]);
});

test('semantic digest ignores volatile modification timestamps', () => {
  const first = { gmtModified: 1, pages: [{ b: 2, a: 1 }] };
  const second = { pages: [{ a: 1, b: 2 }], gmtModified: 999 };
  assert.deepEqual(stableValue(first), stableValue(second));
  assert.equal(digest(first), digest(second));
});

test('findCanvasComponent discovers nested YidaCodeCanvas', () => {
  const canvas = { componentName: 'YidaCodeCanvas', props: { runtimeCode: 'code', importedModules: [] } };
  const descriptor = { componentName: 'YidaCodeCanvas', package: '@ali/vc-deep-yida' };
  assert.equal(findCanvasComponent({ pages: [{ componentsMap: [descriptor], tree: [canvas] }] }), canvas);
  assert.equal(findCanvasComponent({ pages: [] }), null);
});

test('Tailwind build keeps generated CSS out of author source', () => {
  const authorSource =
    "import React from 'react';\nimport './styles.css';\nimport { getLabPageUrl } from '@yida-lab/runtime';\nexport default React.Fragment;\n";
  const output = createCanvasPublishSource(authorSource, '.lab-grid{display:grid}', {
    'tailwind.runtime': '/APP_TEST/workbench/FORM_RUNTIME',
  });
  assert.match(authorSource, /import '\.\/styles\.css'/);
  assert.doesNotMatch(authorSource, /GENERATED_TAILWIND_CSS/);
  assert.doesNotMatch(output, /import '\.\/styles\.css'/);
  assert.match(output, /Generated by npm run build:canvas\. Do not edit\./);
  assert.match(output, /const GENERATED_TAILWIND_CSS/);
  assert.match(output, /const YIDA_LAB_PAGE_ROUTES/);
  assert.match(output, /FORM_RUNTIME/);
  assert.match(output, /\.lab-grid\{display:grid\}/);
});

test('Canvas build injects logical page routes only into generated output', () => {
  const authorSource =
    "import { getLabPageUrl } from '@yida-lab/runtime';\nconst url = getLabPageUrl('page.two');\nexport default url;\n";
  const output = createCanvasRuntimeSource(authorSource, {
    'page.two': '/APP_TEST/workbench/FORM_TWO',
  });
  assert.doesNotMatch(authorSource, /APP_TEST|FORM_TWO/);
  assert.doesNotMatch(output, /@yida-lab\/runtime/);
  assert.match(output, /\/APP_TEST\/workbench\/FORM_TWO/);
});

test('page route map uses logical keys and supports target-free public builds', () => {
  const manifest = {
    application: { appType: 'APP_TEST' },
    pages: [
      { key: 'page.one', formUuid: 'FORM_ONE' },
      { key: 'page.two', formUuid: null },
    ],
  };
  assert.deepEqual(createPageRouteMap(manifest), {
    'page.one': '/APP_TEST/workbench/FORM_ONE',
    'page.two': '#unconfigured-page=page.two',
  });
  assert.throws(() => createPageRouteMap(manifest, { requireRemote: true }), /page.two/);
});

test('tracked Tailwind author source uses a normal CSS import', async () => {
  const authorSource = await fs.readFile(
    new URL('../labs/canvas-tailwind/src/TailwindBuildTimeProbe.canvas.jsx', import.meta.url),
    'utf8',
  );
  assert.match(authorSource, /import '\.\/styles\.css'/);
  assert.match(authorSource, /from '@yida-lab\/runtime'/);
  assert.doesNotMatch(authorSource, /GENERATED_TAILWIND_CSS/);
  assert.doesNotMatch(authorSource, /__TAILWIND_CSS_JSON__/);
});

test('live guard allows only a blank page without a baseline', () => {
  assert.deepEqual(
    assessLiveBaseline({
      baseline: null,
      appType: 'APP_TEST',
      formUuid: 'FORM_TEST',
      liveSemanticSha256: 'blank',
      runtimeCode: '',
    }),
    { mode: 'initial-blank-page' },
  );
  assert.throws(
    () =>
      assessLiveBaseline({
        baseline: null,
        appType: 'APP_TEST',
        formUuid: 'FORM_TEST',
        liveSemanticSha256: 'occupied',
        runtimeCode: 'existing code',
      }),
    /停止首次发布/,
  );
});

test('live guard blocks drift and accepts an exact baseline', () => {
  const baseline = {
    appType: 'APP_TEST',
    formUuid: 'FORM_TEST',
    liveSemanticSha256: 'expected',
  };
  assert.deepEqual(
    assessLiveBaseline({
      baseline,
      appType: 'APP_TEST',
      formUuid: 'FORM_TEST',
      liveSemanticSha256: 'expected',
      runtimeCode: 'code',
    }),
    { mode: 'baseline-match' },
  );
  assert.throws(
    () =>
      assessLiveBaseline({
        baseline,
        appType: 'APP_TEST',
        formUuid: 'FORM_TEST',
        liveSemanticSha256: 'changed',
        runtimeCode: 'code',
      }),
    /线上页面已偏离/,
  );
});
